### ISSUE TITLE
Messages being sent are not using the message layout

### ISSUE THREAD

**Issue by ronydj** [haf/NLog.RabbitMQ#24]
Hi guys,
On the integration with logstash, I need to store things as the process ID. Usually I put the process id on the message layout. But when I started to use the rabbitmq plugin with nlog, I am seeing that you the plugin is getting only the formatted message, and loses all the message layout.

Is there any way to get the proper message layout, or do I need to rewrite this point of formatting the message before the plugin sends it through the rabbitmq ?

**Comment by haf** [comment]
@ronydj I didn't catch this ticket when you opened it; I have two answers for you:

 1. To answer your question, I recommend not formatting the **message** because that's not searchable -- instead add the process Id as a property on the log line dto.
 2. I recommend moving to https://github.com/logary/logary which is much more versatile and actively developed - this repo is being maintained through PRs.
